# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c8bfe059975fc9db5ce3f0c2f8515c720cc710e7333524fd626937ce49ad9a88a2bd438bb49ac5dd106e1a4703ad3a5c37a3fe910de6246949052680fea0c169

test:
  secret_key_base: 3e25b448302ec91b25df21ced2acaa1d3684bf409b2acf69eac1d345ec0debdacd7ff4a2a10089b6f10c6152f0af974e64dec21a455f9e78ba2ec53cc6d80534

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
